### ISSUE TITLE
Improve logic

### ISSUE THREAD

**Issue by Maikuolan** [Lablnet/PHP-MYSQL-Manipulation-Class#1]
Loop operation here isn't making use of the only value being iterated (`$i`):

```PHP
				for($i=1;$i<=$count_rows;$i++){
						$data[$keys] = $value;
					}
```

`if() {..}` code block and `else {..}` code block here do same thing:

```PHP
				if($increment == $count_rows) {
						$columns [] = "{$keys} = '{$values}'";
				} else {
						$columns [] = "{$keys} = '{$values}'";
				}
```

Don't need `else {..}` after `return` (if the code block containing the `return` executes, the `else {..}` will never execute anyway; code immediately following a code block containing a `return` statement is effectively implied as `else {..}`):

```PHP
		if(isset($name) && !empty($name)){
			$sql = "CREATE DATABASE IF NOT EXISTS `{$name}`";
			$this->db->exec($sql);
			return true;
			
		}else{
			return false;
		}
```

**Comment by lablnet** [comment]
Hello @Maikuolan 
If lets say user not provide name so its return false try to run this how you say thats?
![screenshot 196](https://user-images.githubusercontent.com/27757785/39861178-3aa52d56-5459-11e8-9c2f-c8deaef53a7d.png)
![screenshot 197](https://user-images.githubusercontent.com/27757785/39861180-3c47d974-5459-11e8-90da-2656c13ac32c.png)

**Comment by lablnet** [comment]
@Maikuolan send poll request for further its for issue not for improvement

**Comment by Maikuolan** [comment]
Not at all "invalid", and very wrong IMO, but your project and codebase, so your choice. *Closing.*

**Comment by Lablnet** [comment]
I provide you proof detail, so you also have to? How you say when if statement have return else not work?

**Comment by lablnet** [comment]
@Maikuolan i am not say you not allow contribute once i provide code that else statement work even if has return because of condition false you cant reply of this?

**Comment by Maikuolan** [comment]
You ignore my suggestions, label the issue "invalid", and when I accept this and close the issue, you delete my reply, and then lock the issue? I am not interested in participating anymore. If you care, read the PHP docs. Otherwise, do what you want. I will not reply anymore, because I know you will delete my replies, and I don't want to waste my time. I am also unsubscribing from this issue. Good day.

**Comment by lablnet** [comment]
My dear brother if you want suggest you much have open poll request
And. again how you say else not ever work when if has return?

**Comment by lablnet** [comment]
I will change the label once you reply how you say that i ask above?
